#pragma once

#include <FLCore/Common/Unknown.hpp>
#include <FLCore/FLCoreDefs.hpp>

#include <FLCore/Common/CObjects/CObject.hpp>
#include <FLCore/Server/IObject/IObjectInspect.hpp>

struct _FILETIME;

IMPORT bool operator!=(const Rect&, const Rect&);

IMPORT void AppendMissionLogData(const FmtStr*, u8*&, int&, int);
IMPORT u32 Arch2Good(u32);
IMPORT void BaseDataList_destroy();
IMPORT BaseDataList* BaseDataList_get();
IMPORT void BaseDataList_load();
IMPORT void BaseDataList_load_market_data(const char*);
IMPORT void BuildDirectory(const char*);
IMPORT f32 CHATTER_MAX_DIST;
IMPORT f32 CHATTER_MAX_DIST_ATTEN;
IMPORT f32 CHATTER_START_ATTEN;
IMPORT f32 COLLISION_DAMAGE_FACTOR;
IMPORT int COMM_CONFLICT_PRIORITY_CUTOFF;
IMPORT f32 COMM_PLAYER_FAR_DIST;
IMPORT f32 COMM_PLAYER_FAR_DIST_ATTEN;
IMPORT class Behavior* CREATE_BEHAVIOR(int);
IMPORT void CleanUpDatabases();
IMPORT void CompoundInstanceAnalyze(long, void (*)(long, void*), void*);
IMPORT int CompoundInstanceCount(long);
IMPORT long CompoundInstanceFindFirstName(long, const char*);
IMPORT void CompoundInstanceList(long, int*, long**);
IMPORT void ComputeExplosiveImpulses(long, Vector&, Vector&, Vector&);
IMPORT bool CostumeGenderAdjust(int*, int);
IMPORT bool Costume_is_equal(const struct Costume&, const struct Costume&);
IMPORT u32 CreateID(const char*);

IMPORT f32 Csys_error(const Csys&, const Csys&);
IMPORT Csys Csys_identity();
IMPORT Csys Csys_init(const Vector&, const Matrix&);
IMPORT Csys Csys_interpolate(Csys, Csys, f32);

IMPORT void DAEngine_create_filesystem(const char*, struct IFileSystem**, const char*);
IMPORT void DAEngine_release_filesystem(IFileSystem**);
IMPORT Csys DALib_Engine_get_csys(long);
IMPORT void DALib_Engine_set_csys(long, const Csys&);

IMPORT ID_String DEATH_COMM_FUSE;
IMPORT f64 DaysPerSecond;
IMPORT void DebugPrint(const char*, ...);
IMPORT u32 DecodeType(const char*);
IMPORT void ExtractMissionLogData(FmtStr*, u8*&, int&);
IMPORT f32 FIRE_FAILED_DELAY;
IMPORT ID_String FIRE_FAILED_SOUND;

struct HardpointInfo;
IMPORT long FindChild(long, const char*);
IMPORT bool FindHardpoint(long, const char*, long&);
IMPORT bool FindHardpoint_OS(long, const char*, long&, HardpointInfo&);
IMPORT bool FindHardpoint_PS(long, const char*, long&, HardpointInfo&);
IMPORT void FreeCostumeDescriptions();
IMPORT void FreeSpatial(ISpatialPartition*);
IMPORT bool FrustumCull(const Geometry::Frustum&, const Universe::IZone*);
IMPORT IBehaviorManager* GetBehaviorManager(IObjRW*);
IMPORT const CostumeDescriptions* GetCostumeDescriptions();
IMPORT Matrix GetDirectionMatrix(const Transform&, const Vector&);
IMPORT void GetFileSysPath(char*, const char*, IFileSystem*);
IMPORT const char* GetFullFilename(const char*);
IMPORT long GetRoot(long);
IMPORT CObject* GetRoot(const CObject*);
IMPORT bool GetScreenShotPath(char* const);
IMPORT f32 GetSphereIntersectVol(f32, f32, f32);
IMPORT bool GetUserDataPath(char* const);
IMPORT bool GetUserLocalDataPath(char* const);
IMPORT void GiveClientRunPermission();
IMPORT void GiveServerRunPermission();
IMPORT u32 Good2Arch(u32);
IMPORT void GoodList_destroy();
IMPORT GoodInfoList* GoodList_get();
IMPORT void GoodList_load(const char*);
IMPORT bool HardpointPosition(long, const char*, Vector*, Matrix*);
IMPORT bool HardpointPositionA(long, const char*, Vector*, Matrix*);
IMPORT void HardpointToObject(long, HardpointInfo&);
IMPORT void HardpointToWorld(long, HardpointInfo&);
IMPORT void HexToWide(const char*, u16*);
IMPORT bool InitializeRichText(int);
IMPORT bool IsDescendant(long, long);
IMPORT bool IsMPServer();
IMPORT f32 JETTISONED_CARGO_VELOCITY;
IMPORT bool JointEnumCallback(long, long, const struct JointInfo*, void*);
IMPORT f32 LOOT_OWNER_SAFE_TIME;
IMPORT f32 LOOT_UNSEEN_LIFE_TIME;
IMPORT f32 LOOT_UNSEEN_RADIUS;
IMPORT bool LayoutRichText(TextRenderContext&, const RenderDisplayList&, int, RenderDisplayList&, int, int, bool, int*, bool);
IMPORT void LoadBodypartDescriptions(const char*);
IMPORT void LoadCostumeDescriptions(const char*);
IMPORT Matrix LookMatrix(const Vector&);
IMPORT Matrix LookMatrixYup(const Vector&);
IMPORT int MAX_PLAYER_AMMO;
IMPORT f32 MUSIC_CROSS_FADE_DELAY;
IMPORT f32 MUZZLE_CONE_ANGLE;
IMPORT u16 MakeId(const char*);
IMPORT u32 MakeLocationID(u32, const char*);
IMPORT ISpatialPartition* NewSpatial(const char*);
IMPORT int NumHardpoints(long, bool);
IMPORT f32 PLAYER_ATTACHED_EQUIP_HIT_PTS_SCALE;
IMPORT f32 PLAYER_COLLISION_GROUP_HIT_PTS_SCALE;
IMPORT int PackMissionLogData(int, const FmtStr*, u8*, int);
IMPORT _GUID* ParseGUID(const char*, _GUID*);
IMPORT f64 ParseNumber(const char*);
IMPORT void PetalDB_destroy();
IMPORT const PetalInterfaceDatabase* PetalDB_get();
IMPORT void PetalDB_load(const char*);
IMPORT bool PlayerTrailAvailable;
IMPORT Rect RECT_to_Rect(const tagRECT&);
IMPORT Vector RandomVector(f32);
IMPORT Vector random_inside_box(f32, f32, f32);
IMPORT Vector random_inside_cylinder(f32, f32);
IMPORT Vector random_inside_ellipsoid(f32, f32, f32);
IMPORT Vector random_inside_ring(f32, f32, f32);
IMPORT Vector random_inside_sphere(f32);
IMPORT Vector random_on_unit_sphere();
IMPORT Vector random_sphere_constrained(const Vector&, f32);
IMPORT Vector random_sphere_constrained_2(const Vector&, f32, f32);
IMPORT bool ReadConstants(const char*);
IMPORT tagRECT Rect_to_RECT(const Rect&);
IMPORT struct ViewRect Rect_to_ViewRect(const Rect&);
IMPORT void RefreshLoadingProgress();
IMPORT void RegisterLoadingScreen(class ILoadingScreen*);
IMPORT void ReinitializeRichTextFonts();
IMPORT Matrix RotateMatrix(const Vector&);
//@@@TODO IMPORT u32 const  SMM_CHANGE_STATE;
//@@@TODO IMPORT u32 const  SMM_TIMEOUT;
IMPORT ID_String SND_CARGO_JETTISONED;
//@@@TODO IMPORT u16 const  SUBOBJ_ID_NONE;
//@@@TODO IMPORT u16 const  SUBOBJ_ID_POWER;
//@@@TODO IMPORT u16 const  SUBOBJ_ID_ROOT;
IMPORT ulong SafeWaitForSingleObject(void*, ulong);
IMPORT void SetIsMPServer(bool);
IMPORT void SetMultPlayer(bool);
IMPORT void SetStandardFont(int, const TextRenderContext::FontDesc&);
IMPORT void ShutdownRichText();
IMPORT bool SinglePlayer();
IMPORT ID_String SpaceflightLocationID;
IMPORT bool SphereCull(const Geometry::Sphere&, const Universe::IZone*);
IMPORT char* StringAlloc(const char*, bool);
IMPORT const char* StringIndex(const char*, u32);
IMPORT void StringShutdown();
IMPORT ulong ThornGetRenderType(const struct ThornEntity*, const char*);
IMPORT bool ThornGetUserFloat(struct IScriptEngine*, int, const char*, f32*);
IMPORT bool ThornGetUserInt(IScriptEngine*, int, const char*, int*);
IMPORT const char* ThornGetUserString(IScriptEngine*, int, const char*);
IMPORT void ThornScriptDestroy(IScriptEngine**);
IMPORT Csys ThornScriptGetCsys(IScriptEngine*, const char*);
IMPORT IScriptEngine* ThornScriptLoad(const char*);
IMPORT void ToggleIceCap(bool);
IMPORT f64 ValueNum(const char*, u32);
IMPORT Rect ViewRect_to_Rect(const ViewRect&);
IMPORT f32 WALLA_MAX_DIST;
IMPORT f32 WALLA_MAX_DIST_ATTEN;
IMPORT int WALLA_PRIORITY_CUTOFF;
IMPORT f32 WALLA_START_ATTEN;
IMPORT void WaitForClientRunPermission();
IMPORT void WaitForServerRunPermission();
IMPORT void WideToHex(const u16*, char*);

IMPORT int add_good_item(u32, int, f32, f32, bool, GoodDescList*);
IMPORT bool arch_is_combinable(u32);
IMPORT const u16* filetime_to_wstring(_FILETIME const&);
//@@@ IMPORT struct GoodDesc *  find_good_item(struct GoodDescList *,u32,class MetaNode<struct GoodDesc> * *);
IMPORT long get_projected_bounding_box(struct ICamera*, const Vector&, f32, ViewRect*, f32&);
IMPORT long get_projected_bounding_sphere(ICamera*, const Vector&, f32, f32&, f32&, f32&, f32&);
IMPORT int lex_compare(const RenderDisplayList&, const RenderDisplayList&, bool);
IMPORT const char* malloc_strcpy(char**, const char*);
IMPORT void malloc_strfree(char**);
IMPORT const u16* malloc_wstrcpy(u16**, const u16*);
IMPORT void malloc_wstrfree(u16**);
IMPORT Rect rect_intersect(const Rect&, const Rect&);
IMPORT Rect rect_union(const Rect&, const Rect&);
IMPORT int remove_good_item(u32, int, GoodDescList*);
IMPORT char* safe_strcat(char*, int, const char*);
IMPORT char* safe_strcpy(char*, int, const char*);
IMPORT u16* safe_wcscpy(u16*, int, const u16*);
IMPORT ulong select_option_from_string(char*, const option_spec* const, int, const char*);
IMPORT bool strequal(const char*, const char*);

inline CObject* BaseWatcherToCObject(BaseWatcher* basewatcher) { return reinterpret_cast<CObject*>(basewatcher) + 2; }
inline IObjRW* BaseWatcherToIObjRW(BaseWatcher* basewatcher) { return reinterpret_cast<IObjRW*>(basewatcher) - 2; };
